# See the configuration reference at https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/configuration.md
scheb_two_factor:
  google:
    enabled: true
  trusted_device:
    enabled: true
    lifetime: 5184000
    extend_lifetime: false
    cookie_name: trusted_device
  security_tokens:
    - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken
